[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "http://44.197.228.204:5000/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/products-api/*"
  to = "https://stg2.rhnonprod.com/rh/api/:splat"
  status = 200
  force = true 